### PR TITLE
runtime: Update Boxi runtime to 47

### PR DESCRIPTION
**Pull request by ghost**
- Update Boxi runtime to 47
- Fix appdata papercuts

### CODE REVIEW

**Comment by ghost** [comment]
@bbhtt This is ready for review.

**Comment by ghost** [comment]
@bbhtt Still says:

```
Boxi is potentially unsafe

Arbitrary permissions
Can acquire arbitrary permissions
Uses an end-of-life runtime
The runtime used by this app is no longer receiving security updates
```

**Comment by allisonkarlitskaya** [comment]
Thanks :)

**Comment by bbhtt** [comment]
Started a build.

**Pull request merged**
